### ISSUE TITLE
OOM on google colab

### ISSUE THREAD

**Issue by virentakia** [mzbac/qlora-fine-tune#3]
Running the following command on google colab A100 - high RAM:
`python merge_peft_adapters.py --device cpu --base_model_name_or_path tiiuae/falcon-40b-instruct --peft_model_path ./output/checkpoint-2250/adapter_model --output_dir ./merged_models/
`

adapter_config.json:
`{
  "base_model_name_or_path": "tiiuae/falcon-40b-instruct",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "lora_alpha": 16,
  "lora_dropout": 0.1,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 64,
  "revision": null,
  "target_modules": [
    "query_key_value",
    "dense",
    "dense_h_to_4h",
    "dense_4h_to_h"
  ],
  "task_type": "CAUSAL_LM"
}`

I get OOM  and the google colab instance crashes.

What config do I need to run this.

**Comment by mzbac** [comment]
It takes around 65G of RAM to merge a 33b model, so I assume it will need around 79G of RAM to merge a Falcon 40b model.

**Comment by mzbac** [comment]
Close the issue for now. Feel free to reopen it if you still have any issues.

**Comment by virentakia** [comment]
Using 83 GB of RAM and it still OOMs
